version: '3.8'

services:
  app:
    build:
      context: .
    env_file: .env # Load environment variables from .env file
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306 # Use the MySQL default port
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '11388:3306' # Map to a different host port, but use 3306 inside the container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
